### ISSUE TITLE
[BUG] LandLaunch working though /b toggle

### ISSUE THREAD

**Issue by Rabidhuman** [Simplicitee/ProjectAddons#4]
**Describe the bug**
Landlaunch is launching players through /b toggle. this actually causes fall dmg as well.

**To Reproduce**
Simply do /b toggle while earth

**Expected behavior**
like air passives it should toggle off
**Versions:**
 - Spigot: [1.14.4]
 - ProjectKorra [1.8.9]
 - ProjectAddons [1.0.5]

**Comment by xNuminousx** [comment]
What is Landlaunch? You mean Catapult?

**Comment by Rabidhuman** [comment]
Not catapult, the LandLaunch passive move added in this patch 1.0.5
https://projectkorra.com/forum/resources/projectaddons.371/updates

**Comment by ItsBlade** [comment]
It also works despite the bending.ability.landlaunch permission set to false. The only way to disable it is to disable bending.earth.passive, but then you can't use density shift... 
also you have to type /b reload for the move to realise the bending.earth.passive permission changed or that you toggled your bending
