### ISSUE TITLE
[BUG] Error console

### ISSUE THREAD

**Issue by Mrkhris** [Simplicitee/ProjectAddons#6]
**Describe the bug**
Error console https://pastebin.com/LvDaQ1C8

**Versions:**
 - Spigot: [1.15.2] LAST BUILD PAPER
 - ProjectKorra [1.8.9]
 - ProjectAddons [1.0.6]

**Comment by FuddlyWubs** [comment]
Did you ever find the fix to this issue? i'm having it as well.
